# Generated by Django 4.2 on 2023-05-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibilities',
            name='work_company',
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['date_create']},
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position_work',
            field=models.CharField(blank=True, max_length=50, verbose_name='Position'),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Responsibilities',
        ),
    ]
